# Meta Data for SEO

## Homepage
title = "It's Technically Useful"
titleSeparator = "-"
titleAddition = "Inclusive, free, and trustworthy tech space!"
description = "A technology blog brought to you by Conservation Colorado."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "github.io"
titleHome = "Conservation Colorado Tech"

## Twitter Cards
twitterSite = "@ConservationCO"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Conservation Colorado"
schemaAuthor = "Oliver Abdulrahim"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/oliverabdulrahim/"
schemaAuthorGitHub = "https://github.com/oliverabdulrahim/"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/ConservationCO"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/ConservationColorado"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480", "720", "1080", "1280", "1600", "2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = ""

# Alert
alert = true
alertDismissable = false
alertText = "🚧 Please excuse the mess... This website is under construction!"

# Edit Page
repoHost = "GitHub"
docsRepo = "https://github.com/ConservationColorado/its-technically-useful"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
sectionNav = ["about", "guides"]

[options]
lazySizes = true
clipBoard = true
instantPage = true
flexSearch = true
searchSectionsShow = []
searchSectionsIndex = []
darkMode = true
bootStrapJs = true
breadCrumb = false
highLight = true
kaTex = false
multilingualMode = false
docsVersioning = false
fullWidth = false
navbarSticky = true
toTopButton = true
scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
[menu.section]
auto = true
collapsibleSidebar = true
